# Documentation
# https://docs.docker.com/compose/compose-file

version: "3"

services:
  # EVENT STORE
  eventstore:
    build:
      context: 'eventstore'
    restart: always
    hostname: eventstore
    ports:
      - 2113:2113
      - 1113:1113
    network_mode: bridge
    healthcheck:
      test: ['CMD', 'WGET', '--spider', 'http://localhost:2113']
  zoo1:
    build:
      context: 'zookeeper'
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: "server.1=zoo1:2888:3888"
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/dat
      - ./zk-single-kafka-single/zoo1/datalog:/datalog
    network_mode: bridge
    healthcheck:
      test: ['CMD', 'pgrep', 'zoo1']
  kafka1:
    build:
      context: 'kafka'
    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-zoo1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    expose:
      - 9092
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    links:
      - zoo1
    healthcheck:
      test: ['CMD', 'pgrep', 'kafka1']
    network_mode: bridge
