# Documentation
# https://docs.docker.com/compose/compose-file

version: '3'

services:
  # EVENT STORE
  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    expose:
      - 2113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    network_mode: bridge
  # DATABASE - MYSQL
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    network_mode: bridge
  # API - VISPEECH
  vispeech:
    build:
      context: "."
    command: ${CONTAINER_COMMAND}
    restart: always
    # deploy: 
    #   mode: replicated
    #   replicas: ${CONTAINER_SCALE}
    depends_on:
      - eventstore
      - mongodb
    # env_file:
    #   - "./.env"
    environment:
      - EVENT_STORE_HOSTNAME=eventstore
    ports:
      - 80:80
    expose:
      - 80
    # volumes:
    #   - "./src:/app/src"
    links:
      - eventstore
      - mysql
    network_mode: bridge