# Documentation
# https://docs.docker.com/compose/compose-file

version: '3'

services:
  # EVENT STORE
  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    expose:
      - 2113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    networks: 
      - backend 
  # DATABASE - MYSQL
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'vispeech'
      MYSQL_USER: 'vispeech'
      MYSQL_PASSWORD: 'vispeech'
    ports: 
      - 3306:3306
    expose: 
      - 3306
    networks: 
      - backend
  # API - VISPEECH
  vispeech:
    build:
      context: "."
    command: ${CONTAINER_COMMAND}
    restart: always
    deploy: 
      mode: replicated
      replicas: ${CONTAINER_SCALE}
    depends_on:
      - eventstore
      - mysql
    # env_file:
    #   - "./.env"
    environment:
      - EVENT_STORE_HOSTNAME=eventstore
    ports:
      - "${CONTAINER_PORT}:7070"
    expose: 
      - ${CONTAINER_PORT}
    volumes:
      - "./src:/app/src"
    links:
      - eventstore
      - mysql
    networks: 
      - backend
networks:
  backend:
    driver: bridge
