# Documentation
# https://docs.docker.com/compose/compose-file

version: '3'

services:
  # EVENT STORE
  eventstore:
     image: eventstore/eventstore
     ports:
       - 2113:2113
       - 1113:1113
     expose:
       - 2113
     environment:
       - EVENTSTORE_RUN_PROJECTIONS=All
       - EVENTSTORE_START_STANDARD_PROJECTIONS=true
     network_mode: bridge
  # DATABASE - MYSQL
  mongodb:
     image: mongo
     restart: alwaysw
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: mongodb
     ports:
       - 27017:27017
     network_mode: bridge
  # API - VISPEECH
  # vispeech:
  #   build:
  #     context: "."
  #   command: ${CONTAINER_COMMAND}
  #   restart: always
  #   depends_on:
  #     - eventstore
  #     - mongodb
  #   environment:
  #     - EVENT_STORE_HOSTNAME=eventstore
  #   ports:
  #     - ${VISPEECH_PORT}:${VISPEECH_PORT}
  #   expose:
  #     - ${VISPEECH_PORT}
  #   links:
  #     - eventstore
  #     - mongodb
  #   network_mode: bridge
  vispeechdemo:
    build:
      context: "./ViSpeechDemo"
    command: "npm start"
    restart: always
    depends_on:
      - eventstore
      - mongodb
      - vispeech
    ports:
      - ${VISPEECH_PORT_DEMO}:${VISPEECH_PORT_DEMO}
    expose:
      - ${VISPEECH_PORT_DEMO}
    links:
      - eventstore
      - mongodb
      - vispeech
    network_mode: bridge
  release:
    build:
      context: "./release"
    command: "npm start"
    restart: always
    depends_on:
      - eventstore
      - mongodb
      - vispeech
    ports:
      - ${RELEASE_PAGE_PORT}:${RELEASE_INTERNAL_PORT}
    expose:
      - ${RELEASE_PAGE_PORT}
    links:
      - eventstore
      - mongodb
      - vispeech
    network_mode: bridge
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    build: .
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock