# Documentation
# https://docs.docker.com/compose/compose-file

version: "3"

services:
  # EVENT STORE
  eventstore:
    image: eventstore/eventstore:release-5.0.3
    ports:
      - 2113:2113
      - 1113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    network_mode: bridge
    healthcheck:
      test: ['CMD', 'WGET', '--spider', 'http://localhost:2113']
  # DATABASE - MYSQL
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_DATABASE: vispeech
    ports:
      - 27017:27017
    network_mode: bridge
    healthcheck:
      test: ['CMD', 'pgrep', 'mongo']
  core:
    build:
      context: : "./src/core"
    restart: always
    ports:
      - 5000:5000
    expose:
      - 5000
    network_mode: bridge
  # API - VISPEECH
  vispeech:
    build:
      context: "./src/server"
    command: "npm start:prod"
    restart: always
    depends_on:
      - eventstore
      - mongodb
    environment:
      - EVENT_STORE_HOSTNAME=eventstore
    ports:
      - 7070:7070
    expose:
      - 7070
    links:
      - eventstore
      - mongodb
    network_mode: bridge
  vispeechui:
    build:
      context: "./src/client"
    command: "npm start:prod"
    restard: always
    depends_on:
      - eventstore
      - mongodb
      - vispeech
    ports:
      - 3200:3200
    expose:
      - 3200
    network_mode: bridge
  vispeechdemo:
    build:
      context: "./src/demo"
    command: "npm start"
    restart: always
    depends_on:
      - eventstore
      - mongodb
      - vispeech
    ports:
      - 3000:3000
    expose:
      - 3000
    links:
      - eventstore
      - mongodb
    #  - vispeech
    network_mode: bridge
  vispeechrelease:
    build:
      context: "./src/demo"
    command: "npm start"
    restart: always
    depends_on:
      - eventstore
      - mongodb
      - vispeech
    ports:
      - 80:80
    expose:
      - 80
    links:
      - eventstore
      - mongodb
    #  - vispeech
    network_mode: bridge
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=1
      - ZOO_PORT=2181
      - ZOO_SERVERS=server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/dat
      - ./zk-single-kafka-single/zoo1/datalog:/datalog
    network_mode: bridge
    healthcheck:
      test: ['CMD', 'pgrep', 'zoo1']
  kafka1:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka1
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-zoo1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    links:
      - zoo1
    healthcheck:
      test: ['CMD', 'pgrep', 'kafka1']
    network_mode: bridge
