version: 2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "ui/package.json" }}
  - &run
    run:
      name: LS
      command: ls /home/circleci/vispeech/src/client/package.json
  - &install-deps
    run:
      name: Install dependencies
      command: cd ui/ && npm i
  - &build-packages
    run:
      name: Build
      command: npm run build --prefix ui/

jobs:
  build:
    working_directory: ~/vispeech/src/client
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/vispeech
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "ui/package.json" }}
      - run:
          name: Install dependencies
          command: npm i && cd ui && npm i
      - save_cache:
          key: dependency-cache-{{ checksum "ui/package.json" }}
          paths:
            - ~/vispeech/src/client/ui/node_modules
      - run:
          name: Build
          command: npm run build --prefix ui/

  test_node_12:
    working_directory: ~/vispeech/src/client
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/vispeech
      - *run
      - *restore-cache
      - *install-deps
      - *build-packages

workflows:
  version: 2
  build-and-test:
    jobs:
      - build